# Generated by Django 4.0.1 on 2022-01-06 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mainUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='User.mainusers')),
            ],
        ),
    ]
